/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedKhataRouteImport } from './routes/_authenticated/khata'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKhataCustomerIdRouteImport } from './routes/_authenticated/khata.$customerId'

const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/_authenticated/transactions',
    path: '/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/_authenticated/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/_authenticated/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKhataRoute = AuthenticatedKhataRouteImport.update({
  id: '/_authenticated/khata',
  path: '/khata',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/_authenticated/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKhataCustomerIdRoute =
  AuthenticatedKhataCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedKhataRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/khata': typeof AuthenticatedKhataRouteWithChildren
  '/pos': typeof AuthenticatedPosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/khata/$customerId': typeof AuthenticatedKhataCustomerIdRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/khata': typeof AuthenticatedKhataRouteWithChildren
  '/pos': typeof AuthenticatedPosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/khata/$customerId': typeof AuthenticatedKhataCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/khata': typeof AuthenticatedKhataRouteWithChildren
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/khata/$customerId': typeof AuthenticatedKhataCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/inventory'
    | '/khata'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/khata/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/inventory'
    | '/khata'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/khata/$customerId'
  id:
    | '__root__'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/khata'
    | '/_authenticated/pos'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/_authenticated/khata/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedKhataRoute: typeof AuthenticatedKhataRouteWithChildren
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/khata': {
      id: '/_authenticated/khata'
      path: '/khata'
      fullPath: '/khata'
      preLoaderRoute: typeof AuthenticatedKhataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/khata/$customerId': {
      id: '/_authenticated/khata/$customerId'
      path: '/$customerId'
      fullPath: '/khata/$customerId'
      preLoaderRoute: typeof AuthenticatedKhataCustomerIdRouteImport
      parentRoute: typeof AuthenticatedKhataRoute
    }
  }
}

interface AuthenticatedKhataRouteChildren {
  AuthenticatedKhataCustomerIdRoute: typeof AuthenticatedKhataCustomerIdRoute
}

const AuthenticatedKhataRouteChildren: AuthenticatedKhataRouteChildren = {
  AuthenticatedKhataCustomerIdRoute: AuthenticatedKhataCustomerIdRoute,
}

const AuthenticatedKhataRouteWithChildren =
  AuthenticatedKhataRoute._addFileChildren(AuthenticatedKhataRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedKhataRoute: AuthenticatedKhataRouteWithChildren,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
